export const VIETNAM_PROVINCES = [
  "An Giang",
  "Bà Rịa – Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP. Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái"
];

export const AREA_COEFFICIENTS = {
  FOUNDATION: {
    'Móng đơn(20%)': 0.2,
    'Móng cọc (30%)': 0.3,
    'Móng băng (40%)': 0.4,
    'Móng bè (60%)': 0.6,
    'Móng băng 2 phương (60%)': 0.6,
  },
  BASEMENT: {
    'DT từ 70m2: Sâu >=1.7 đến 2m (200%)': 2.0,
    'DT từ 70m2: Sâu 1 đến 1.3m (150%)': 1.5,
    'DT từ 70m2: Sâu >=2m (220%)': 2.2,
    'DT nhỏ 70m2: Sâu 1 đến 1.3m (170%)': 1.7,
    'DT nhỏ 70m2: Sâu >=1.7 đến 2m (220%)': 2.2,
    'DT nhỏ 70m2: Sâu >=2m (240%)': 2.4,
  },
  GROUND_FLOOR: {
    'Nền BTCT (+20%)': 1.2,
    'Nền BT gạch vỡ (Chuẩn)': 1.0,
  },
  FLOOR: 1.0,
  MEZZANINE: 1.0,
  TERRACE: {
    'Không tiểu cảnh (50%)': 0.5,
    'Có tiểu cảnh (70%)': 0.7,
  },
  TUM: 1.0,
  VOID: {
    'Lớn hơn 8m2 (50%)': 0.5,
    'Nhỏ hơn bằng 8m2 (100%)': 1.0,
  },
  ROOF: {
    'Mái BTCT (50%)': 0.5,
    'Mái tôn (30%)': 0.3,
    'Lam sắt, nhôm, gỗ, BTCT (30%)': 0.3,
    'Mái kính khung sắt (nhôm) (50%)': 0.5,
    'Mái BTCT nghiêng (70%)': 0.7,
    'Vì kèo lợp ngói 30 độ (70%)': 0.7,
    'Vì kèo lợp ngói 45 độ (100%)': 1.0,
    'Mái BTCT dán ngói 30 độ (100%)': 1.0,
    'Mái BTCT dán ngói 45 độ (130%)': 1.3,
  },
  YARD: {
    'Không có mái che (70%)': 0.7,
    'Có mái che (100%)': 1.0,
  },
};

export const PRICE_COEFFICIENTS = {
  SMALL_AREA: {
    '30-40m2': 0.05,
    '40-50m2': 0.04,
    '50-60m2': 0.025,
    '60-70m2': 0.01,
    'Lớn hơn 70m2': 0,
  },
  FACADES: {
    'Một mặt tiền': 0,
    'Hai mặt tiền': 0.02,
    'Ba mặt tiền': 0.04,
  },
  BUILDING_TYPE: {
    'Nhà phố': 0,
    'Nhà cấp 4': -0.15,
    'Biệt thự': 0.15,
  },
  ARCHITECTURE_TYPE: {
    'Hiện đại': 0,
    'Cổ điển, tân cổ điển': 0.05,
  },
  LAND_POSITION: {
    'Xây chen, các phía đã có nhà': 0,
    'Đất trống 1 bên': 0.01,
    'Đất trống 2 bên': 0.02,
    'Đất trống 3 bên': 0.025,
  },
  SMALL_ALLEY: {
    'Hẻm dưới 2m': 0.05,
    'Hẻm 2-3m': 0.04,
    'Hẻm 3-4m': 0.03,
    'Hẻm 4-5m': 0.02,
    'Hẻm 5-6m': 0.01,
    'Đường xe tải': 0,
  },
  DIFFICULT_CONDITION: 0.04,
  SPLIT_LEVEL: 0.02,
};
