import { EstimateItem } from './types';

export interface TemplateItem {
  id: string;
  stt: string;
  hang_muc: string;
  dvt: string;
  chung_loai: string;
  dinh_muc_m2: number;
  don_gia_tham_khao: number;
  isParent: boolean;
}

export const TEMPLATE_DU_TOAN: TemplateItem[] = [
  // 1. CHI PHÍ TỔ CHỨC SẢN XUẤT
  { id: '1', stt: '1', hang_muc: 'Chi phí tổ chức sản xuất', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '1.1', stt: '1.1', hang_muc: 'Chi phí lao động', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '1.1.1', stt: '1.1.1', hang_muc: 'Nhân công xây dựng trực tiếp', dvt: 'vnđ', chung_loai: 'Tổng diện tích xây dựng x Đơn giá nhân công', dinh_muc_m2: 1.001, don_gia_tham_khao: 1800000, isParent: false },
  { id: '1.1.2', stt: '1.1.2', hang_muc: 'Lương kỹ sư hiện trường', dvt: 'vnđ', chung_loai: 'Tổng chi phí trực tiếp x Tỷ lệ %', dinh_muc_m2: 0.040, don_gia_tham_khao: 0, isParent: false },
  { id: '1.2', stt: '1.2', hang_muc: 'Chi phí quản lý', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '1.2.1', stt: '1.2.1', hang_muc: 'Chi phí quản lý của nhà thầu', dvt: 'vnđ', chung_loai: 'Tổng chi phí trực tiếp x Tỷ lệ %', dinh_muc_m2: 0.043, don_gia_tham_khao: 0, isParent: false },
  { id: '1.2.2', stt: '1.2.2', hang_muc: 'Chi phí hỗ trợ thi công', dvt: 'vnđ', chung_loai: 'Tổng chi phí trực tiếp x Tỷ lệ %', dinh_muc_m2: 0.036, don_gia_tham_khao: 0, isParent: false },
  { id: '1.2.3', stt: '1.2.3', hang_muc: 'Chi phí dự phòng rủi ro', dvt: 'vnđ', chung_loai: 'Tổng chi phí trực tiếp x Tỷ lệ %', dinh_muc_m2: 0.020, don_gia_tham_khao: 0, isParent: false },

  // 2. CHI PHÍ VẬT LIỆU THÔ
  { id: '2', stt: '2', hang_muc: 'Chi phí vật liệu thô', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '2.1', stt: '2.1', hang_muc: 'Chi phí vật liệu xây dựng', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '2.1.1', stt: '2.1.1', hang_muc: 'Thép xây dựng', dvt: 'kg', chung_loai: 'Việt Nhật/ Pomina', dinh_muc_m2: 38.039, don_gia_tham_khao: 15300, isParent: false },
  { id: '2.1.2', stt: '2.1.2', hang_muc: 'Xi măng', dvt: 'kg', chung_loai: 'INSEE/Hà Tiên', dinh_muc_m2: 120.123, don_gia_tham_khao: 1680, isParent: false },
  { id: '2.1.3', stt: '2.1.3', hang_muc: 'Đá 1 x 2', dvt: 'm3', chung_loai: 'Đồng Nai/ Địa phương', dinh_muc_m2: 0.230, don_gia_tham_khao: 450000, isParent: false },
  { id: '2.1.4', stt: '2.1.4', hang_muc: 'Đá 4x6', dvt: 'm3', chung_loai: 'Đồng Nai/ Địa phương', dinh_muc_m2: 0.010, don_gia_tham_khao: 360000, isParent: false },
  { id: '2.1.5', stt: '2.1.5', hang_muc: 'Cát vàng bê tông hạt lớn', dvt: 'm3', chung_loai: 'Đồng Nai/ Địa phương', dinh_muc_m2: 0.160, don_gia_tham_khao: 450000, isParent: false },
  { id: '2.1.6', stt: '2.1.6', hang_muc: 'Cát xây tô hạt mịn', dvt: 'm3', chung_loai: 'Đồng Nai/ Địa phương', dinh_muc_m2: 0.190, don_gia_tham_khao: 450000, isParent: false },
  { id: '2.1.7', stt: '2.1.7', hang_muc: 'Cát nền', dvt: 'm3', chung_loai: 'Đồng Nai/ Địa phương', dinh_muc_m2: 0.200, don_gia_tham_khao: 302400, isParent: false },
  { id: '2.1.8', stt: '2.1.8', hang_muc: 'Gạch xây', dvt: 'viên', chung_loai: 'Tuynen/ Địa phương', dinh_muc_m2: 145.149, don_gia_tham_khao: 1200, isParent: false },
  { id: '2.1.9', stt: '2.1.9', hang_muc: 'Dung dịch chống thấm', dvt: 'kg', chung_loai: 'Kova CT11A/ Sika latex', dinh_muc_m2: 1.301, don_gia_tham_khao: 43200, isParent: false },
  { id: '2.2', stt: '2.2', hang_muc: 'Chi phí vật liệu âm tường, sàn', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '2.2.1', stt: '2.2.1', hang_muc: 'Ống thoát nước PVC các loại', dvt: 'm', chung_loai: 'Bình Minh/ Tiền Phong', dinh_muc_m2: 0.350, don_gia_tham_khao: 28000, isParent: false },
  { id: '2.2.2', stt: '2.2.2', hang_muc: 'Ống cấp nước lạnh PPR các loại', dvt: 'm', chung_loai: 'Bình Minh/ Tiền Phong', dinh_muc_m2: 0.501, don_gia_tham_khao: 35000, isParent: false },
  { id: '2.2.3', stt: '2.2.3', hang_muc: 'Dây điện các loại', dvt: 'm', chung_loai: 'Cadivi', dinh_muc_m2: 4.004, don_gia_tham_khao: 7500, isParent: false },
  { id: '2.2.4', stt: '2.2.4', hang_muc: 'Tủ điện chống giật', dvt: 'cái', chung_loai: 'ELCB Panasonic', dinh_muc_m2: 0.010, don_gia_tham_khao: 1200000, isParent: false },
  { id: '2.2.5', stt: '2.2.5', hang_muc: 'Ống ruột gà', dvt: 'm', chung_loai: 'Sino/ MPE', dinh_muc_m2: 0.501, don_gia_tham_khao: 15000, isParent: false },
  { id: '2.2.6', stt: '2.2.6', hang_muc: 'Ống cứng luồn dây điện âm sàn', dvt: 'm', chung_loai: 'VEGA', dinh_muc_m2: 1.001, don_gia_tham_khao: 13000, isParent: false },
  { id: '2.2.7', stt: '2.2.7', hang_muc: 'Cáp điện thoại, truyền hình', dvt: 'm', chung_loai: 'Sino/ MPE', dinh_muc_m2: 0.300, don_gia_tham_khao: 4000, isParent: false },
  { id: '2.2.8', stt: '2.2.8', hang_muc: 'Cáp internet AMP CAT5', dvt: 'm', chung_loai: 'Sino/ MPE', dinh_muc_m2: 0.250, don_gia_tham_khao: 6000, isParent: false },
  { id: '2.2.9', stt: '2.2.9', hang_muc: 'Tôn lợp', dvt: 'm2', chung_loai: 'Hoa Sen', dinh_muc_m2: 0, don_gia_tham_khao: 130000, isParent: false },
  { id: '2.2.10', stt: '2.2.10', hang_muc: 'Phụ kiện nước các loại', dvt: 'cái', chung_loai: 'Bình Minh/ Tiền Phong', dinh_muc_m2: 3.003, don_gia_tham_khao: 15000, isParent: false },
  { id: '2.2.11', stt: '2.2.11', hang_muc: 'Hộp nối', dvt: 'cái', chung_loai: 'Sino/ MPE', dinh_muc_m2: 2.002, don_gia_tham_khao: 6000, isParent: false },
  { id: '2.2.12', stt: '2.2.12', hang_muc: 'Bể tự hoại', dvt: 'cái', chung_loai: 'Tiêu chuẩn nhà phố', dinh_muc_m2: 0.002, don_gia_tham_khao: 6000000, isParent: false },
  { id: '2.2.13', stt: '2.2.13', hang_muc: 'Ống đồng máy lạnh', dvt: 'm', chung_loai: 'Ống Thái Lan 7gem', dinh_muc_m2: 0.200, don_gia_tham_khao: 90000, isParent: false },
  { id: '2.2.14', stt: '2.2.14', hang_muc: 'Ống thoát nước ngưng máy lạnh', dvt: 'm', chung_loai: 'Bình Minh', dinh_muc_m2: 0.501, don_gia_tham_khao: 7000, isParent: false },
  { id: '2.2.15', stt: '2.2.15', hang_muc: 'Ngói lợp', dvt: 'm2', chung_loai: 'Đồng tâm/ Khác', dinh_muc_m2: 0, don_gia_tham_khao: 250000, isParent: false },
  { id: '2.2.16', stt: '2.2.16', hang_muc: 'Khung kèo mái', dvt: 'm2', chung_loai: 'Thép nhẹ', dinh_muc_m2: 0, don_gia_tham_khao: 350000, isParent: false },

  // 3. CHI PHÍ VẬT LIỆU HOÀN THIỆN
  { id: '3', stt: '3', hang_muc: 'Chi phí vật liệu hoàn thiện', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '3.1', stt: '3.1', hang_muc: 'Gạch ốp lát', dvt: '', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '3.1.1', stt: '3.1.1', hang_muc: 'Gạch lát nền các tầng', dvt: 'm2', chung_loai: 'Bạch Mã, Viglacera, Taca, Taicera', dinh_muc_m2: 0.471, don_gia_tham_khao: 200000, isParent: false },
  { id: '3.1.2', stt: '3.1.2', hang_muc: 'Gạch nền sân thượng, sân trước sau, ban công', dvt: 'm2', chung_loai: 'Bạch Mã, Viglacera, Taca, Taicera', dinh_muc_m2: 0.082, don_gia_tham_khao: 200000, isParent: false },
  { id: '3.1.3', stt: '3.1.3', hang_muc: 'Gạch nền WC', dvt: 'm2', chung_loai: 'Bạch Mã, Viglacera, Taca, Taicera', dinh_muc_m2: 0.033, don_gia_tham_khao: 200000, isParent: false },
  { id: '3.1.4', stt: '3.1.4', hang_muc: 'Gạch ốp tường WC', dvt: 'm2', chung_loai: 'Bạch Mã, Viglacera, Taca, Taicera', dinh_muc_m2: 0.123, don_gia_tham_khao: 200000, isParent: false },
  { id: '3.1.5', stt: '3.1.5', hang_muc: 'Gạch ốp tường khu bếp', dvt: 'm2', chung_loai: 'Bạch Mã, Viglacera, Taca, Taicera', dinh_muc_m2: 0.041, don_gia_tham_khao: 200000, isParent: false },
  { id: '3.1.6', stt: '3.1.6', hang_muc: 'Gạch ốp tường mặt tiền, cửa chính', dvt: 'm2', chung_loai: 'Bạch Mã, Viglacera, Taca, Taicera', dinh_muc_m2: 0.041, don_gia_tham_khao: 200000, isParent: false },
  { id: '3.1.7', stt: '3.1.7', hang_muc: 'Keo chà ron', dvt: 'kg', chung_loai: 'Weber', dinh_muc_m2: 0.167, don_gia_tham_khao: 20000, isParent: false },
  { id: '3.1.8', stt: '3.1.8', hang_muc: 'Gạch ốp trang trí khác (sân vườn)', dvt: 'm2', chung_loai: 'Granite, Hoa cương', dinh_muc_m2: 0.041, don_gia_tham_khao: 200000, isParent: false },
  { id: '3.1.9', stt: '3.1.9', hang_muc: 'Xoa nền hầm', dvt: 'm2', chung_loai: 'Xoa nền Hadener', dinh_muc_m2: 0.165, don_gia_tham_khao: 300000, isParent: false },
  { id: '3.2', stt: '3.2', hang_muc: 'Sơn nước', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '3.2.1', stt: '3.2.1', hang_muc: 'Sơn ngoài trời (02 lớp Matit, 01 lót, 02 phủ)', dvt: 'm2', chung_loai: 'Maxilite/ Expo bột trét Việt Mỹ ngoài nhà', dinh_muc_m2: 0.707, don_gia_tham_khao: 100000, isParent: false },
  { id: '3.2.2', stt: '3.2.2', hang_muc: 'Sơn trong nhà (02 lớp Matit, 01 lót, 02 phủ)', dvt: 'm2', chung_loai: 'Maxilite/ Expo bột trét Việt Mỹ trong nhà', dinh_muc_m2: 1.885, don_gia_tham_khao: 80000, isParent: false },
  { id: '3.3', stt: '3.3', hang_muc: 'Thiết bị điện', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '3.3.1', stt: '3.3.1', hang_muc: 'MCB các loại', dvt: 'cái', chung_loai: 'Sino/ MPE', dinh_muc_m2: 0.035, don_gia_tham_khao: 300000, isParent: false },
  { id: '3.3.2', stt: '3.3.2', hang_muc: 'Công tắc các loại', dvt: 'cái', chung_loai: 'Sino/ MPE', dinh_muc_m2: 0.041, don_gia_tham_khao: 100000, isParent: false },
  { id: '3.3.3', stt: '3.3.3', hang_muc: 'Ổ cắm các loại', dvt: 'cái', chung_loai: 'Sino/ MPE', dinh_muc_m2: 0.056, don_gia_tham_khao: 100000, isParent: false },
  { id: '3.3.4', stt: '3.3.4', hang_muc: 'Ổ cắm điện thoại, internet, truyền hình cáp', dvt: 'cái', chung_loai: 'Sino/ MPE', dinh_muc_m2: 0.016, don_gia_tham_khao: 100000, isParent: false },
  { id: '3.3.5', stt: '3.3.5', hang_muc: 'Đèn chiếu sáng trong phòng, ngoài sân', dvt: 'cái', chung_loai: 'Philips/ Led', dinh_muc_m2: 0.023, don_gia_tham_khao: 175000, isParent: false },
  { id: '3.3.6', stt: '3.3.6', hang_muc: 'Đèn cầu thang', dvt: 'cái', chung_loai: 'Philips/ Led', dinh_muc_m2: 0.010, don_gia_tham_khao: 500000, isParent: false },
  { id: '3.3.7', stt: '3.3.7', hang_muc: 'Đèn ốp trần ban công, sân thượng', dvt: 'cái', chung_loai: 'Philips/ Led', dinh_muc_m2: 0.006, don_gia_tham_khao: 250000, isParent: false },
  { id: '3.3.8', stt: '3.3.8', hang_muc: 'Đèn hắt trang trí trần thạch cao', dvt: 'md', chung_loai: 'Led', dinh_muc_m2: 0.576, don_gia_tham_khao: 65000, isParent: false },
  { id: '3.3.9', stt: '3.3.9', hang_muc: 'Đèn downlight âm trần', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.123, don_gia_tham_khao: 195000, isParent: false },
  { id: '3.3.10', stt: '3.3.10', hang_muc: 'Đèn chùm', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.002, don_gia_tham_khao: 1500000, isParent: false },
  { id: '3.3.11', stt: '3.3.11', hang_muc: 'Switch 12 port 10/100/1000', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.002, don_gia_tham_khao: 850000, isParent: false },
  { id: '3.3.12', stt: '3.3.12', hang_muc: 'Bộ phận sóng Wifi', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.010, don_gia_tham_khao: 450000, isParent: false },
  { id: '3.3.13', stt: '3.3.13', hang_muc: 'Camera gắn tường', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.010, don_gia_tham_khao: 950000, isParent: false },
  { id: '3.3.14', stt: '3.3.14', hang_muc: 'Đầu thu hồi hình 512Gb', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.002, don_gia_tham_khao: 3000000, isParent: false },
  { id: '3.3.15', stt: '3.3.15', hang_muc: 'Quạt trần', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.006, don_gia_tham_khao: 2500000, isParent: false },
  { id: '3.3.16', stt: '3.3.16', hang_muc: 'Quạt hút âm trần WC', dvt: 'cái', chung_loai: 'Việt Nam/ Trung Quốc', dinh_muc_m2: 0.008, don_gia_tham_khao: 350000, isParent: false },
  { id: '3.4', stt: '3.4', hang_muc: 'Thiết bị vệ sinh - nước', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '3.4.1', stt: '3.4.1', hang_muc: 'Bàn Cầu', dvt: 'cái', chung_loai: 'Inax, Viglacera, Caesar', dinh_muc_m2: 0.008, don_gia_tham_khao: 3500000, isParent: false },
  { id: '3.4.2', stt: '3.4.2', hang_muc: 'Lavabo + bộ xả', dvt: 'cái', chung_loai: 'Inax, Viglacera, Caesar', dinh_muc_m2: 0.008, don_gia_tham_khao: 1600000, isParent: false },
  { id: '3.4.3', stt: '3.4.3', hang_muc: 'Vòi xả lavabo nóng lạnh', dvt: 'cái', chung_loai: 'Vòi lạnh Viglacera, Caesar, Javic', dinh_muc_m2: 0.008, don_gia_tham_khao: 1200000, isParent: false },
  { id: '3.4.4', stt: '3.4.4', hang_muc: 'Vòi sen tắm đứng WC', dvt: 'cái', chung_loai: 'Vòi lạnh Viglacera, Caesar, Javic', dinh_muc_m2: 0.008, don_gia_tham_khao: 1650000, isParent: false },
  { id: '3.4.5', stt: '3.4.5', hang_muc: 'Vòi xịt WC', dvt: 'cái', chung_loai: 'Vòi lạnh Viglacera, Caesar, Javic', dinh_muc_m2: 0.008, don_gia_tham_khao: 250000, isParent: false },
  { id: '3.4.6', stt: '3.4.6', hang_muc: 'Vòi xả sân thượng, ban công, sân, WC', dvt: 'cái', chung_loai: 'Vòi lạnh Viglacera, Caesar, Javic', dinh_muc_m2: 0.016, don_gia_tham_khao: 100000, isParent: false },
  { id: '3.4.7', stt: '3.4.7', hang_muc: 'Các phụ kiện WC (Gương, móc đồ, kệ xà bông)', dvt: 'bộ', chung_loai: 'Việt Nam', dinh_muc_m2: 0.008, don_gia_tham_khao: 950000, isParent: false },
  { id: '3.4.8', stt: '3.4.8', hang_muc: 'Phễu thu sàn', dvt: 'cái', chung_loai: 'Inox chống hôi', dinh_muc_m2: 0.016, don_gia_tham_khao: 100000, isParent: false },
  { id: '3.4.9', stt: '3.4.9', hang_muc: 'Cầu chắn rác', dvt: 'cái', chung_loai: 'Inox', dinh_muc_m2: 0.006, don_gia_tham_khao: 100000, isParent: false },
  { id: '3.4.10', stt: '3.4.10', hang_muc: 'Chậu rửa chén 2 ngăn', dvt: 'cái', chung_loai: 'Đại Thành, Luxta, Javic', dinh_muc_m2: 0.002, don_gia_tham_khao: 2500000, isParent: false },
  { id: '3.4.11', stt: '3.4.11', hang_muc: 'Vòi rửa chén nóng lạnh', dvt: 'cái', chung_loai: 'Đại Thành, Luxta, Erowin', dinh_muc_m2: 0.002, don_gia_tham_khao: 1200000, isParent: false },
  { id: '3.4.12', stt: '3.4.12', hang_muc: 'Bồn nước inox và chân bồn', dvt: 'cái', chung_loai: 'Tân Á Đại Thành 1000 lít', dinh_muc_m2: 0.002, don_gia_tham_khao: 3700000, isParent: false },
  { id: '3.4.13', stt: '3.4.13', hang_muc: 'Máy bơm nước', dvt: 'cái', chung_loai: 'Panasonic - 200W', dinh_muc_m2: 0.002, don_gia_tham_khao: 1500000, isParent: false },

  // 4. CHI PHÍ GIAO KHOÁN
  { id: '4', stt: '4', hang_muc: 'Chi phí giao khoán (vật liệu và nhân công)', dvt: '', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.1', stt: '4.1', hang_muc: 'Cửa đi - cửa sổ - vách kính', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.1.1', stt: '4.1.1', hang_muc: 'Cửa phòng 1 cánh', dvt: 'm2', chung_loai: 'Nhôm/ nhựa lõi thép/ gỗ', dinh_muc_m2: 0.018, don_gia_tham_khao: 1700000, isParent: false },
  { id: '4.1.2', stt: '4.1.2', hang_muc: 'Cửa WC', dvt: 'm2', chung_loai: 'Nhôm/ nhựa lõi thép', dinh_muc_m2: 0.012, don_gia_tham_khao: 1700000, isParent: false },
  { id: '4.1.3', stt: '4.1.3', hang_muc: 'Cửa đi 4 cánh cửa chính', dvt: 'm2', chung_loai: 'Nhôm/ nhựa lõi thép/ gỗ', dinh_muc_m2: 0.018, don_gia_tham_khao: 2250000, isParent: false },
  { id: '4.1.4', stt: '4.1.4', hang_muc: 'Cửa sau, hông, ban công, sân thượng', dvt: 'm2', chung_loai: 'Nhôm/ nhựa lõi thép/ gỗ', dinh_muc_m2: 0.006, don_gia_tham_khao: 2250000, isParent: false },
  { id: '4.1.5', stt: '4.1.5', hang_muc: 'Cửa sổ các loại', dvt: 'm2', chung_loai: 'Nhôm/ nhựa lõi thép', dinh_muc_m2: 0.016, don_gia_tham_khao: 2250000, isParent: false },
  { id: '4.1.6', stt: '4.1.6', hang_muc: 'Cửa Cổng', dvt: 'm2', chung_loai: 'Cửa sắt sơn dầu, mẫu đơn giản', dinh_muc_m2: 0.022, don_gia_tham_khao: 1600000, isParent: false },
  { id: '4.1.7', stt: '4.1.7', hang_muc: 'Cửa cuốn, cửa kéo', dvt: 'm2', chung_loai: 'Việt Nam/ Trung quốc', dinh_muc_m2: 0, don_gia_tham_khao: 950000, isParent: false },
  { id: '4.1.8', stt: '4.1.8', hang_muc: 'Khung sắt bảo vệ ô cửa sổ mặt tiền', dvt: 'm2', chung_loai: 'Sắt hộp mạ kẽm gia công theo thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 950000, isParent: false },
  { id: '4.1.9', stt: '4.1.9', hang_muc: 'Vách kính cố định', dvt: 'm2', chung_loai: 'Nhôm/ nhựa lõi thép', dinh_muc_m2: 0, don_gia_tham_khao: 1400000, isParent: false },
  { id: '4.1.10', stt: '4.1.10', hang_muc: 'Khóa cửa phòng, chính, ban công, sân thượng', dvt: 'cái', chung_loai: 'Khóa tay nắm tròn hoặc gạt', dinh_muc_m2: 0, don_gia_tham_khao: 450000, isParent: false },
  { id: '4.1.11', stt: '4.1.11', hang_muc: 'Khóa cửa WC', dvt: 'cái', chung_loai: 'Khóa tay nắm tròn hoặc gạt', dinh_muc_m2: 0, don_gia_tham_khao: 450000, isParent: false },
  { id: '4.1.12', stt: '4.1.12', hang_muc: 'Khóa cửa cổng', dvt: 'cái', chung_loai: 'Khóa móc hoặc khác', dinh_muc_m2: 0, don_gia_tham_khao: 350000, isParent: false },
  { id: '4.1.13', stt: '4.1.13', hang_muc: 'Vách kính phòng tắm', dvt: 'm2', chung_loai: 'Theo thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 1400000, isParent: false },
  { id: '4.2', stt: '4.2', hang_muc: 'Cầu thang (Bao gồm vật tư và nhân công)', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.2.1', stt: '4.2.1', hang_muc: 'Lan can cầu thang', dvt: 'md', chung_loai: 'Kính cường lực/ Sắt/ Gỗ/ Inox', dinh_muc_m2: 0.046, don_gia_tham_khao: 1650000, isParent: false },
  { id: '4.2.2', stt: '4.2.2', hang_muc: 'Tay vịn cầu thang', dvt: 'md', chung_loai: 'Tay vịn gỗ sồi D50', dinh_muc_m2: 0, don_gia_tham_khao: 450000, isParent: false },
  { id: '4.2.3', stt: '4.2.3', hang_muc: 'Trụ cầu thang', dvt: 'cái', chung_loai: 'Gỗ sồi', dinh_muc_m2: 0, don_gia_tham_khao: 2500000, isParent: false },
  { id: '4.3', stt: '4.3', hang_muc: 'Đá granite (bao gồm vật tư và nhân công)', dvt: 'vnđ', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.3.1', stt: '4.3.1', hang_muc: 'Đá Granite mặt cầu thang', dvt: 'm2', chung_loai: 'Đá Trắng Suối Lau, Hồng Phan Rang, Tím Hoa Cà', dinh_muc_m2: 0.103, don_gia_tham_khao: 1250000, isParent: false },
  { id: '4.3.2', stt: '4.3.2', hang_muc: 'Đá Granite tam cấp, ngạch cửa', dvt: 'm2', chung_loai: 'Đá Trắng Suối Lau, Hồng Phan Rang, Tím Hoa Cà', dinh_muc_m2: 0.013, don_gia_tham_khao: 1250000, isParent: false },
  { id: '4.3.3', stt: '4.3.3', hang_muc: 'Đá Granite ốp thang máy', dvt: 'm2', chung_loai: 'Đá Trắng Suối Lau, Hồng Phan Rang, Tím Hoa Cà', dinh_muc_m2: 0, don_gia_tham_khao: 1250000, isParent: false },
  { id: '4.3.4', stt: '4.3.4', hang_muc: 'Đá Granite mặt tiền tầng trệt', dvt: 'm2', chung_loai: 'Đá Trắng Suối Lau, Hồng Phan Rang, Tím Hoa Cà', dinh_muc_m2: 0.021, don_gia_tham_khao: 1250000, isParent: false },
  { id: '4.3.5', stt: '4.3.5', hang_muc: 'Len bậc cầu thang', dvt: 'md', chung_loai: 'Đá Trắng Suối Lau, Hồng Phan Rang, Tím Hoa Cà', dinh_muc_m2: 0.062, don_gia_tham_khao: 250000, isParent: false },
  { id: '4.4', stt: '4.4', hang_muc: 'Đóng trần', dvt: '', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.4.1', stt: '4.4.1', hang_muc: 'Thạch cao trang trí', dvt: 'm2', chung_loai: 'khung M29 Vĩnh Tường , Tấm Gyproc Vĩnh Tường', dinh_muc_m2: 0.504, don_gia_tham_khao: 165000, isParent: false },
  { id: '4.4.2', stt: '4.4.2', hang_muc: 'Trần nhựa', dvt: 'm2', chung_loai: 'Theo y/c thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 155000, isParent: false },
  { id: '4.5', stt: '4.5', hang_muc: 'Hệ kim khí (sắt, gỗ, inox,...)', dvt: '', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.5.1', stt: '4.5.1', hang_muc: 'Lan can ban công, tầng lửng', dvt: 'm', chung_loai: 'Lan can sắt hộp , mẫu đơn giản', dinh_muc_m2: 0.022, don_gia_tham_khao: 1500000, isParent: false },
  { id: '4.5.2', stt: '4.5.2', hang_muc: 'Khung sắt mái lấy sáng cầu thang, lỗ thông tầng', dvt: 'm2', chung_loai: 'Sắt hộp 20x20x1.0mm sơn dầu/ Tấm lợp kính cường lực 8ly', dinh_muc_m2: 0.032, don_gia_tham_khao: 1450000, isParent: false },
  { id: '4.5.3', stt: '4.5.3', hang_muc: 'Lam trang trí mặt tiền, sân thượng', dvt: 'm2', chung_loai: 'Gia công theo thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 1450000, isParent: false },
  { id: '4.5.4', stt: '4.5.4', hang_muc: 'Mái đón khung thép', dvt: 'm2', chung_loai: 'Khung thép sơn hoàn thiện theo thiết kế', dinh_muc_m2: 0.036, don_gia_tham_khao: 1450000, isParent: false },
  { id: '4.5.5', stt: '4.5.5', hang_muc: 'Mái Poly lấy sáng', dvt: 'm2', chung_loai: 'Gia công theo thiết kế', dinh_muc_m2: 0.015, don_gia_tham_khao: 1450000, isParent: false },
  { id: '4.6', stt: '4.6', hang_muc: 'Thiết bị và nội thất', dvt: '', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.6.1', stt: '4.6.1', hang_muc: 'Tủ kệ bếp trên, bếp dưới', dvt: 'md', chung_loai: 'Gỗ MDF An Cường/ Ba Thanh lõi xanh chống ẩm phủ Melamine', dinh_muc_m2: 0, don_gia_tham_khao: 6500000, isParent: false },
  { id: '4.6.2', stt: '4.6.2', hang_muc: 'Nội thất (giường, tủ, kệ, quầy bar)', dvt: 'món', chung_loai: 'Tính riêng từng món', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.6.3', stt: '4.6.3', hang_muc: 'Thang máy', dvt: 'vnđ', chung_loai: 'Theo y/c thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.6.4', stt: '4.6.4', hang_muc: 'Thang máy tăng thêm mỗi tầng', dvt: 'điểm dừng', chung_loai: 'Theo y/c thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.6.5', stt: '4.6.5', hang_muc: 'Máy nước nóng trực tiếp', dvt: 'cái', chung_loai: 'Panasosic/Khác', dinh_muc_m2: 0.008, don_gia_tham_khao: 4500000, isParent: false },
  { id: '4.6.6', stt: '4.6.6', hang_muc: 'Máy điều hòa cục bộ 1 chiều lạnh 1.0HP', dvt: 'cái', chung_loai: 'Daikin/ Panasonic', dinh_muc_m2: 0.008, don_gia_tham_khao: 10590000, isParent: false },
  { id: '4.6.7', stt: '4.6.7', hang_muc: 'Máy điều hòa cục bộ 1 chiều lạnh 1.5HP', dvt: 'cái', chung_loai: 'Daikin/ Panasonic', dinh_muc_m2: 0.002, don_gia_tham_khao: 14000000, isParent: false },
  { id: '4.6.8', stt: '4.6.8', hang_muc: 'Giá đỡ cục nóng điều hòa', dvt: 'cái', chung_loai: 'Việt Nam', dinh_muc_m2: 0.008, don_gia_tham_khao: 650000, isParent: false },
  { id: '4.6.9', stt: '4.6.9', hang_muc: 'Máy nước nóng năng lượng mặt trời', dvt: 'cái', chung_loai: 'Tân Á Đại Thành, Hướng Dương 130L', dinh_muc_m2: 0.002, don_gia_tham_khao: 6500000, isParent: false },
  { id: '4.6.10', stt: '4.6.10', hang_muc: 'Mô tơ bình lưu điện cửa cuốn', dvt: 'cái', chung_loai: 'Việt Nam/ Trung quốc', dinh_muc_m2: 0.002, don_gia_tham_khao: 8000000, isParent: false },
  { id: '4.7', stt: '4.7', hang_muc: '4.7. KHÁC', dvt: '', chung_loai: '', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: true },
  { id: '4.7.1', stt: '4.7.1', hang_muc: 'Hồ bơi', dvt: 'm2', chung_loai: 'Theo y/c thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.7.2', stt: '4.7.2', hang_muc: 'Hòn non bộ và tiểu cảnh', dvt: 'm2', chung_loai: 'Theo y/c thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.7.3', stt: '4.7.3', hang_muc: 'Sơn hiệu ứng bê tông', dvt: 'm2', chung_loai: 'Theo y/c thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 500000, isParent: false },
  { id: '4.7.4', stt: '4.7.4', hang_muc: 'Ép cọc', dvt: 'md', chung_loai: 'Theo y/c thiết kế', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.7.5', stt: '4.7.5', hang_muc: 'Chi phí cừ chống đổ nhà hàng xóm', dvt: 'vnđ', chung_loai: 'Trọn gói (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.7.6', stt: '4.7.6', hang_muc: 'Chi phí bản vẽ xin phép xây dựng', dvt: 'vnđ', chung_loai: 'Trọn gói (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.7.7', stt: '4.7.7', hang_muc: 'Chi phí dịch vụ xin phép xây dựng', dvt: 'vnđ', chung_loai: 'Trọn gói (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.7.8', stt: '4.7.8', hang_muc: 'Chi phí thiết kế bản vẽ 2D', dvt: 'vnđ', chung_loai: 'Trọn gói (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 0, isParent: false },
  { id: '4.7.9', stt: '4.7.9', hang_muc: 'Chi phí nâng nền', dvt: 'm3', chung_loai: 'Theo khối lượng nâng nền thực tế (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 450000, isParent: false },
  { id: '4.7.10', stt: '4.7.10', hang_muc: 'Chi phí nguồn điện 3 pha cho thang máy', dvt: 't/b', chung_loai: 'Trọn gói (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 10000000, isParent: false },
  { id: '4.7.11', stt: '4.7.11', hang_muc: 'Chi phí dây TE, cọc tiếp địa', dvt: 't/b', chung_loai: 'Trọn gói (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 12000000, isParent: false },
  { id: '4.7.12', stt: '4.7.12', hang_muc: 'Chi phí ép cừ gia cố vách hầm', dvt: 'm', chung_loai: 'Tính theo chu vi hầm', dinh_muc_m2: 0, don_gia_tham_khao: 3300000, isParent: false },
  { id: '4.7.13', stt: '4.7.13', hang_muc: 'Chi phí chống mối cho công trình', dvt: 'm2', chung_loai: 'Tính theo diện tích đất (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 200000, isParent: false },
  { id: '4.7.14', stt: '4.7.14', hang_muc: 'Chi phí vệ sinh công nghiệp', dvt: 'm2', chung_loai: 'Tính theo m2 sàn (nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 200000, isParent: false },
  { id: '4.7.15', stt: '4.7.15', hang_muc: 'Chi phí tháo dỡ nhà, cũ', dvt: 't/b', chung_loai: '(nếu có)', dinh_muc_m2: 0, don_gia_tham_khao: 15000000, isParent: false },
];

export const dataExcelGoc: EstimateItem[] = [];
